F_IC_WEGSEGMENT = [
    'Shape@', 'WS_OIDN', 'WS_UIDN', 'WS_GIDN', 'STATUS', 'LBLSTATUS', 'MORF', 'LBLMORF', 'WEGCAT', 'LBLWEGCAT',
    'LSTRNMID', 'LSTRNM', 'RSTRNMID', 'RSTRNM', 'BEHEER', 'LBLBEHEER', 'METHODE', 'LBLMETHOD', 'OPNDATUM',
    'BEGINTIJD', 'BEGINORG', 'LBLBGNORG', 'TGBEP', 'LBLTGBEP', 'legende', 'bron'
]
F_IC_NATIONALEWEG = [
    'NW_OIDN', 'WS_OIDN', 'IDENT2', 'BEGINTIJD', 'BEGINORG', 'LBLBGNORG'
]
F_IC_GENUMMERDEWEG = [
    'GW_OIDN', 'WS_OIDN', 'IDENT8', 'RICHTING', "LBLRICHT", "VOLGNUMMER", 'BEGINTIJD', 'BEGINORG', 'LBLBGNORG'
]
F_IC_RIJSTROKEN = [
    'RS_OIDN', 'WS_OIDN', 'WS_GIDN', 'AANTAL', 'RICHTING', 'LBLRICHT',
    'VANPOS', 'TOTPOS', 'BEGINTIJD', 'BEGINORG', 'LBLBGNORG'
]
F_IC_WEGBREEDTE = [
    'WB_OIDN', 'WS_OIDN', 'WS_GIDN', 'BREEDTE',
    'VANPOS', 'TOTPOS', 'BEGINTIJD', 'BEGINORG', 'LBLBGNORG'
]
F_IC_WEGVERHARDING = [
    'WV_OIDN', 'WS_OIDN', 'WS_GIDN', 'TYPE', 'LBLTYPE',
    'VANPOS', 'TOTPOS', 'BEGINTIJD', 'BEGINORG', 'LBLBGNORG'
]